version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=challenge_db
    ports:
      - '${PORT_DB}:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./script_db:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports: 
      - '${PORT_UI_DB}:8080'
volumes:
  db:
    driver: local